#!/bin/bash

# Builds the prod version of the Jekyll site.

# Exit on first failing command.
set -e
# Echo commands to console.
set -x
# Exit on unset variable.
set -u

BUNDLE_GEMFILE=Gemfile JEKYLL_ENV=production bundle exec jekyll build \
  --config _config.yml,_config_prod.yml
