#!/bin/bash

# Echo commands to console.
set -x
# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

BUILD_DIR=public

# Skips validation checks that take a long time.
htmlproofer_args_extra=""
if [ "${1-}" = "--quick" ]; then
  htmlproofer_args_extra="--disable-external"
else
  htmlproofer_args_extra="--check-external-hash"
fi

function join_by {
  local IFS="$1"
  shift
  echo "$*"
}

# Ignore the following URLs because they get 403 errors from CI intermittently.
IGNORE_PATTERNS=()
IGNORE_PATTERNS+=("/vimeo.com/")
IGNORE_PATTERNS+=("/upwork.com/")
IGNORE_PATTERNS+=("/www.amd.com/")
IGNORE_PATTERNS+=("/mediagoblin-v5lmqis51k.herokuapp.com/")
IGNORE_PATTERNS+=("/servernope.com/")
IGNORE_PATTERNS+=("/gusto.com/")
IGNORE_PATTERNS+=("/vmware.com/")
IGNORE_PATTERNS+=("/medium.com/")
IGNORE_PATTERNS+=("/typeform.com/")
IGNORE_PATTERNS+=("/www.sciencedirect.com/")
IGNORE_PATTERNS+=("/developer.github.com/")
IGNORE_PATTERNS+=("/docs.github.com/")

URL_IGNORE="$(join_by , "${IGNORE_PATTERNS[@]}")"

# Run HTMLProofer
htmlproofer "$BUILD_DIR" \
  --only-4xx \
  --check-favicon \
  --check-html \
  --check-opengraph \
  --allow-hash-href \
  --empty-alt-ignore \
  --file-ignore "public/collect-debt/full-emails/index.html" \
  `# Swap URLs https://mtlynch.io/ for / so that htmlproofer checks the local` \
  `# build rather than the production URLs. At the time this check runs, the` \
  `# site has not yet deployed, so htmlproofer shouldn't try to hit the real` \
  `# mtlynch.io server to verify that URLs are present.` \
  --url-swap "https\://mtlynch.io/:/" \
  --url-ignore "${URL_IGNORE}" \
  `# Some sites return HTTP 400/429 - No Error when HTMLProofer sends ` \
  `# requests, so ignore those.` \
  --http-status-ignore "400,429" \
  "$htmlproofer_args_extra"
