#!/bin/sh

# Uses Markdown Linter to find issues in markdown files.

# Note that we use sh instead of bash because only sh is available
# in some markdownlint Docker images.

markdownlint "./content/**/*.md"
