#!/bin/bash

# Echo commands to console.
set -x
# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

BUILD_DIR=public

# Skips validation checks that take a long time.
htmlproofer_args_extra=""
if [ "${1-}" = "--quick" ]; then
  htmlproofer_args_extra="--disable-external"
else
  htmlproofer_args_extra="--check-external-hash"
fi

# Run HTMLProofer
htmlproofer "$BUILD_DIR" \
  --only-4xx \
  --check-favicon \
  --check-html \
  --check-opengraph \
  --allow-hash-href \
  --empty-alt-ignore \
  --file-ignore "public/collect-debt/full-emails/index.html" \
  `# Swap URLs https://mtlynch.io/ for / so that htmlproofer checks the local` \
  `# build rather than the production URLs. At the time this check runs, the` \
  `# site has not yet deployed, so htmlproofer shouldn't try to hit the real` \
  `# mtlynch.io server to verify that URLs are present.` \
  `# Swap the plaus.js URL with the official Plausible URL to match the ` \
  `# redirect that happens server-side.`
  --url-swap "https\://mtlynch.io/:/,https\://mtlynch.io/plaus.js:https\://plausible.io/js/plausible.js" \
  `# Ignore the following URLs because they get 403 errors from CI` \
  `# intermittently.` \
  --url-ignore "/vimeo.com/,/upwork.com/,/www.amd.com/,/mediagoblin-v5lmqis51k.herokuapp.com/,/servernope.com/,/gusto.com/,/vmware.com/" \
  `# Some sites return HTTP 400/429 - No Error when HTMLProofer sends ` \
  `# requests, so ignore those.` \
  --http-status-ignore "400,429" \
  "$htmlproofer_args_extra"
