#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x
# Exit on unset variable.
set -u

_tests/check-trailing-whitespace
_tests/lint-frontmatter
_tests/lint-markdown

./_build_prod_site

_tests/lint-html "$@"
_tests/check-google-analytics-token
_tests/check-twitter-cards
_tests/check-amazon-links "$@"
