#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x

# Execute Markdown Linter
mdl _posts _pages --style _linter/markdown-linter-style.rb

# Skips validation checks that take a long time
htmlproofer_args_extra=""
if [ "$1" = "--quick" ]; then
  htmlproofer_args_extra="--disable-external"
else
  htmlproofer_args_extra="--check-external-hash"
fi

# Run HTMLProofer
# Ignore vimeo URLs because they get 403 errors from Travis intermittently.
BUNDLE_GEMFILE=Gemfile bundle exec jekyll build \
  --config _config.yml,_config_dev.yml
bundle exec htmlproofer ./_site \
  --only-4xx \
  --check-favicon \
  --check-html \
  --check-opengraph \
  --allow-hash-href \
  --empty-alt-ignore \
  --url-ignore "/vimeo.com/" \
  "$htmlproofer_args_extra"
