#!/bin/bash

# Makes sure large twitter cards appear in the site HTML.

# Echo commands to console.
set -x
# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

if ! egrep "\"twitter:card.*summary_large_image\"" _site/ -R; then
  echo "ERROR: Large Twitter cards didn't appear in site build!";
  exit 1;
fi
