#!/bin/bash

# Checks that Amazon links have the correct tracking ID for this blog.

# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

AMAZON_AFFILIATE_ID=mtlynch-20

shortlinks=$(
  egrep \
    --dereference-recursive \
    --only-matching \
    --no-filename \
    --binary-files=without-match \
    "https?://amzn.to/[^\?\&\"\)]+" \
    _site/ | uniq
  )
echo $(echo "$shortlinks" | wc -l) " Amazon links to check"

for url in $shortlinks; do
  url_effective=$(
    curl $url \
      --silent \
      --location \
      --head \
      --output /dev/null \
      --write-out '%{url_effective}'
   )
  if ! echo "$url_effective" | grep $AMAZON_AFFILIATE_ID; then
    echo "ERROR: Amazon URL missing expected" \
         "affiliate ID (${AMAZON_AFFILIATE_ID}): $url_effective";
    exit 1;
  fi
done

