#!/bin/bash

# Uses Markdown Linter to find issues in markdown files.

# Echo commands to console.
set -x
# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

bundler exec mdl \
  $(find -name "*.md" \
      -not -path "./_vendor/*" \
      -not -path "./node_modules/*" \
      -not -path "./_sections/ads/*") \
  --style _linter/markdown-linter-style.rb
