#!/bin/bash

# Echo commands to console.
set -x
# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

# Execute frontmatter tests.
BUNDLE_GEMFILE=Gemfile bundle exec jekyll yml-test
