#!/bin/bash

# Echo commands to console.
set -x
# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

# Execute Markdown Linter
mdl \
  _posts \
  _pages \
  --style _linter/markdown-linter-style.rb
