#!/usr/bin/env bash

set -eux

#PADDLE_SUBSCRIPTION_ID='sub_01hcq7a0e33vs9ct0thy0nrjg0' # Sandbox
PADDLE_SUBSCRIPTION_ID='sub_01hjxmy7m33j3jmhn9wzpqmx83' # Sandbox
PADDLE_INGREDIENT_PARSE_PRICE_ID='pri_01hd7srv3h2gfccs19c7dy92f0' # Sandbox

curl \
  --request POST \
  --url "https://sandbox-api.paddle.com/subscriptions/${PADDLE_SUBSCRIPTION_ID}/charge/preview" \
  --header "Authorization: Bearer ${PADDLE_AUTH_CODE}" \
  --header 'Content-Type: application/json' \
  --header 'Accept: application/json' \
  --data '{
  "items": [
    {
      "price_id": "'"${PADDLE_INGREDIENT_PARSE_PRICE_ID}"'",
      "quantity": 1
    }
  ],
  "effective_from": "next_billing_period"
}' | python3 -m json.tool

curl \
  --request POST \
  --url "https://sandbox-api.paddle.com/subscriptions/${PADDLE_SUBSCRIPTION_ID}/charge" \
  --header "Authorization: Bearer ${PADDLE_AUTH_CODE}" \
  --header 'Content-Type: application/json' \
  --header 'Accept: application/json' \
  --data '{
  "items": [
    {
      "price_id": "'"${PADDLE_INGREDIENT_PARSE_PRICE_ID}"'",
      "quantity": 1
    }
  ],
  "effective_from": "next_billing_period"
}' | python3 -m json.tool

#curl \
#  --request GET \
#  --url "https://sandbox-api.paddle.com/subscriptions/${PADDLE_SUBSCRIPTION_ID}?include=next_transaction" \
#  --header "Authorization: Bearer ${PADDLE_AUTH_CODE}" \
#  --header 'Content-Type: application/json' \
#  --header 'Accept: application/json' | python3 -m json.tool
