#!/usr/bin/env bash

# Exit script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

find public -type f -name "*.xml" -print0 | while IFS= read -r -d '' file; do
  xmllint --noout --valid "$file"
done
